# demonstrate、dev
mode: dev

spring:
  application:
    name: my-java-project
  servlet:
    multipart:
      max-file-size: 5MB
  thymeleaf:
    cache: false
#  redis:
#    host: 127.0.0.1
#    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.197.72:3306/test?useTimezone=true&serverTimezone=GMT%2B8&useSSL=true&characterEncoding=utf8
    username: root
    password: SCBJ$#^MrfGFPMun

server:
  port: 8888
  servlet:
    context-path: '/api'
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml

es:
  address: 119.29.197.72:9200

img:
  location: D:/Source/UploadImg
  extensions:
    - .jpg
    - .png

whitelist: localhost,127.0.0.1,119.29.197.72