# demonstrate、dev
mode: demonstrate

spring:
  application:
    name: my-java-project
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:59171/test?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root

server:
  port: 8888
  servlet:
    context-path: '/api'
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml

es:
  address: 127.0.0.1:9200

whitelist: 127.0.0.1,0:0:0:0:0:0:0:1