# demonstrate、dev
mode: demonstrate

spring:
  application:
    name: my-java-project
  servlet:
    multipart:
      max-file-size: 2MB
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:59171/test?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root

server:
  port: 8888
  servlet:
    context-path: '/api'
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml

es:
  address: 127.0.0.1:9200

img:
  location: C:/Source/UploadImg
  extensions:
    - .jpg
    - .png

whitelist: 119.29.197.72